export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST"
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS"
export const FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE"

export const FETCH_LOGOUT_REQUEST = "FETCH_LOGOUT_REQUEST"
export const FETCH_LOGOUT_SUCCESS = "FETCH_LOGOUT_SUCCESS"
export const FETCH_LOGOUT_FAILURE = "FETCH_LOGOUT_FAILURE"

export const SOCKECT_LOGIN = "SOCKECT_LOGIN"
export const SOCKECT_LOGOUT = "SOCKECT_LOGOUT"
export const SOCKECT_WRITE = "SOCKECT_WRITE"
export const SOCKECT_MESSAGE = "SOCKECT_MESSAGE"
